"""student.

Revision ID: 3abadb9c3a0f
Revises:
Create Date: 2024-11-18 22:00:27.755949

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3abadb9c3a0f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("student",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("name", sa.String(length=31), nullable=False),
    sa.Column("surname", sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student")
    # ### end Alembic commands ###
